### ISSUE TITLE
Add Overall Timeout policy 

### ISSUE THREAD

**Issue by DashaBulanova** [dodopizza/httpclient-resilience-policies#13]
**Description**
Library uses only timeout-per-try and all responsibility rests with the client.
But It'll be better to add an overall-timeout-policy to concentrate full responsibility in the library.

Suggested ordering of overall-timeout-policy at the below image:

![image](https://user-images.githubusercontent.com/948846/78977000-06b64580-7b20-11ea-8ce8-96d88d182cc2.png)

**All additional information see at:**
https://github.com/App-vNext/Polly/wiki/Timeout
https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-applying-timeouts

**Comment by NYMEZIDE** [comment]
I'll take it when I'm done issue #14.
I read the theory. Everything seems to be clear.

**Comment by Ceridan** [comment]
The tricky part is this [thing](https://github.com/dodopizza/httpclient-resilience-policies/blob/master/src/Dodo.HttpClient.ResiliencePolicies/HttpClientBuilderExtensions.cs#L37). The HttpClient has its own timeout also which could be considered as a kind of overall timeout too. We need to find a way how to make them work together correctly.

**Comment by Ceridan** [comment]
Done. Thanks to @NYMEZIDE 

Will be released in version v2.0.0.

See [milestone v2.0.0](https://github.com/dodopizza/httpclient-resilience-policies/milestone/1)
