### ISSUE TITLE
AddJsonClient doesn't respect clientName parameter

### ISSUE THREAD

**Issue by Ceridan** [dodopizza/httpclient-resilience-policies#25]
`AddJsonClient` extension method provided by the library has `clientName` argument to create named clients but actually never use it.

Actually it is not a bug, it was never implemented. We should fix it.

**Comment by NYMEZIDE** [comment]
взял в работу

**Comment by Ceridan** [comment]
Closed in #35. Thanks to @NYMEZIDE
