### ISSUE TITLE
implement Phi-Accrual Failure Detector for adjust timeout at runtime 

### ISSUE THREAD

**Issue by DashaBulanova** [dodopizza/httpclient-resilience-policies#26]
**Problem description**
The choice of the correct timeout is always a complicated task.

The idea is rather than using a configured constant timeout continually measure response times and automatically adjust timeouts according to the observation of response time distribution. This can be done with a Phi Accrual failure detector algorithm.

**Comment by Ceridan** [comment]
We have tested some approaches and looks like this task is too complicated to implement it in the easy and simple way. Also, I am not sure do we really need to implement it?
@DashaBulanova what do you think?

**Comment by DashaBulanova** [comment]
I think you are absolutely right and we should close this issue.
