### ISSUE TITLE
HttpClientSettings refactoring

### ISSUE THREAD

**Issue by DashaBulanova** [dodopizza/httpclient-resilience-policies#38]
**Problem description**

The first problem is the **name** of `HttpClientSettings` does not reflect the core idea of the library. It would be better PollyDefaultSettings or something like this. 

The second problem is according to framework design guidelines using **constructors** is not very usable in this type of object. It would be better to make **public setters** for all settings.

**Comment by Ceridan** [comment]
Yes, we could change the naming, but I prefer to avoid `PollyDefaultSettings`. I understand that currently we are strongly bound to Polly, but in general case Polly is just an implementation details of our library. We able to replace Polly with something else and save our API for the end-user without changes.

**Comment by Ceridan** [comment]
Closed by #43, #46, #47 

Will be released in version v2.0.0.

See milestone [v2.0.0](https://github.com/dodopizza/httpclient-resilience-policies/milestone/1)
